name: Deploy API to Windows VM

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for the actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script: |
            cd C:/path/to/your/app/directory  # Adjust the path to your app's directory
            git pull origin main  # Pull the latest code
            npm install  # Install dependencies
            pm2 restart server  # Restart the application with PM2 or another process manager
